//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xml.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class copia
    {
        public long cedulasociado { get; set; }
        public string codnit { get; set; }
        public string codempresa { get; set; }
        public string coddependencia { get; set; }
        public string periododeduce { get; set; }
        public Nullable<System.DateTime> fechanacimiento { get; set; }
        public string deduceocacional { get; set; }
        public string sexo { get; set; }
        public string estudios { get; set; }
        public string codprofesion { get; set; }
        public string estadocivil { get; set; }
        public string nroacta { get; set; }
        public Nullable<System.DateTime> fechaacta { get; set; }
        public decimal salario { get; set; }
        public string codempresalabora { get; set; }
        public Nullable<System.DateTime> fechaingresoLabora { get; set; }
        public string tipocontrato { get; set; }
        public Nullable<System.DateTime> fechaterminacontrato { get; set; }
        public string cargo { get; set; }
        public string codbanco { get; set; }
        public string numerocuenta { get; set; }
        public int agencia { get; set; }
        public long codanalista { get; set; }
        public string rutaanalista { get; set; }
        public string tipocuenta { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> ultimaactualizacion { get; set; }
        public string operadoractualizo { get; set; }
        public string paisnace { get; set; }
        public string dptonace { get; set; }
        public string ciudadnace { get; set; }
        public long idnits { get; set; }
        public Nullable<short> idtipovivienda { get; set; }
        public Nullable<byte> szin { get; set; }
        public Nullable<short> idtiposalario { get; set; }
        public string tipopacto { get; set; }
        public Nullable<byte> web { get; set; }
        public decimal idasociados { get; set; }
        public string codigotipo { get; set; }
    }
}
